site_name: Pack 1158
pages:
  - Home: index.md
  - Events:
    - Watermine: events/watermine-back-to-school-blast.md
    - P-Nats Scout Night: events/potomac-nationals-scout-night.md
    - Bottle Rocket Derby: events/soda-bottle-rocket-derby.md
    - Day/Twilight Camp: events/passport-to-adventure.md
  - Resources:
    - Handbook: resources/handbook.md
    - Calendar: resources/calendar.md
    - Packing List: resources/camp-packing-list.md
